# Generated by Django 4.1.6 on 2023-02-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
                ('material', models.CharField(choices=[('Plastico', 'Plastico'), ('Vidrio', 'Vidrio'), ('Ceramica', 'Ceramica')], max_length=20)),
            ],
        ),
    ]
