# Generated by Django 4.1.6 on 2023-04-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0003_alter_position_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(max_length=1500, verbose_name='Descripción'),
        ),
    ]
